// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: generateState.proto

package protoGenerated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StateSubset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginatorIndex         int32 `protobuf:"varint,1,opt,name=OriginatorIndex,proto3" json:"OriginatorIndex,omitempty"`
	PendingMap              int32 `protobuf:"varint,2,opt,name=PendingMap,proto3" json:"PendingMap,omitempty"`
	RerouteMap              int32 `protobuf:"varint,3,opt,name=RerouteMap,proto3" json:"RerouteMap,omitempty"`
	CacheStruct             int32 `protobuf:"varint,4,opt,name=CacheStruct,proto3" json:"CacheStruct,omitempty"`
	SuccessfulFound         int32 `protobuf:"varint,5,opt,name=SuccessfulFound,proto3" json:"SuccessfulFound,omitempty"`
	FailedRequestsThreshold int32 `protobuf:"varint,6,opt,name=FailedRequestsThreshold,proto3" json:"FailedRequestsThreshold,omitempty"`
	FailedRequestsAccess    int32 `protobuf:"varint,7,opt,name=FailedRequestsAccess,proto3" json:"FailedRequestsAccess,omitempty"`
	TimeStep                int32 `protobuf:"varint,8,opt,name=TimeStep,proto3" json:"TimeStep,omitempty"`
}

func (x *StateSubset) Reset() {
	*x = StateSubset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generateState_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateSubset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSubset) ProtoMessage() {}

func (x *StateSubset) ProtoReflect() protoreflect.Message {
	mi := &file_generateState_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSubset.ProtoReflect.Descriptor instead.
func (*StateSubset) Descriptor() ([]byte, []int) {
	return file_generateState_proto_rawDescGZIP(), []int{0}
}

func (x *StateSubset) GetOriginatorIndex() int32 {
	if x != nil {
		return x.OriginatorIndex
	}
	return 0
}

func (x *StateSubset) GetPendingMap() int32 {
	if x != nil {
		return x.PendingMap
	}
	return 0
}

func (x *StateSubset) GetRerouteMap() int32 {
	if x != nil {
		return x.RerouteMap
	}
	return 0
}

func (x *StateSubset) GetCacheStruct() int32 {
	if x != nil {
		return x.CacheStruct
	}
	return 0
}

func (x *StateSubset) GetSuccessfulFound() int32 {
	if x != nil {
		return x.SuccessfulFound
	}
	return 0
}

func (x *StateSubset) GetFailedRequestsThreshold() int32 {
	if x != nil {
		return x.FailedRequestsThreshold
	}
	return 0
}

func (x *StateSubset) GetFailedRequestsAccess() int32 {
	if x != nil {
		return x.FailedRequestsAccess
	}
	return 0
}

func (x *StateSubset) GetTimeStep() int32 {
	if x != nil {
		return x.TimeStep
	}
	return 0
}

type StateSubsets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subset []*StateSubset `protobuf:"bytes,1,rep,name=subset,proto3" json:"subset,omitempty"`
}

func (x *StateSubsets) Reset() {
	*x = StateSubsets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generateState_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateSubsets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSubsets) ProtoMessage() {}

func (x *StateSubsets) ProtoReflect() protoreflect.Message {
	mi := &file_generateState_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSubsets.ProtoReflect.Descriptor instead.
func (*StateSubsets) Descriptor() ([]byte, []int) {
	return file_generateState_proto_rawDescGZIP(), []int{1}
}

func (x *StateSubsets) GetSubset() []*StateSubset {
	if x != nil {
		return x.Subset
	}
	return nil
}

var File_generateState_proto protoreflect.FileDescriptor

var file_generateState_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcd, 0x02, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53,
	0x75, 0x62, 0x73, 0x65, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x6f, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f,
	0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x1e, 0x0a, 0x0a, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x70, 0x12,
	0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x4d, 0x61, 0x70, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x52, 0x65, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x4d, 0x61, 0x70, 0x12,
	0x20, 0x0a, 0x0b, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x12, 0x28, 0x0a, 0x0f, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x46,
	0x6f, 0x75, 0x6e, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x38, 0x0a, 0x17, 0x46,
	0x61, 0x69, 0x6c, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x54, 0x68, 0x72,
	0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x17, 0x46, 0x61,
	0x69, 0x6c, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x54, 0x68, 0x72, 0x65,
	0x73, 0x68, 0x6f, 0x6c, 0x64, 0x12, 0x32, 0x0a, 0x14, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x14, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x73, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x65, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x54, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x65, 0x70, 0x22, 0x34, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x75,
	0x62, 0x73, 0x65, 0x74, 0x73, 0x12, 0x24, 0x0a, 0x06, 0x73, 0x75, 0x62, 0x73, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x53, 0x75, 0x62,
	0x73, 0x65, 0x74, 0x52, 0x06, 0x73, 0x75, 0x62, 0x73, 0x65, 0x74, 0x42, 0x11, 0x5a, 0x0f, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_generateState_proto_rawDescOnce sync.Once
	file_generateState_proto_rawDescData = file_generateState_proto_rawDesc
)

func file_generateState_proto_rawDescGZIP() []byte {
	file_generateState_proto_rawDescOnce.Do(func() {
		file_generateState_proto_rawDescData = protoimpl.X.CompressGZIP(file_generateState_proto_rawDescData)
	})
	return file_generateState_proto_rawDescData
}

var file_generateState_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_generateState_proto_goTypes = []interface{}{
	(*StateSubset)(nil),  // 0: StateSubset
	(*StateSubsets)(nil), // 1: StateSubsets
}
var file_generateState_proto_depIdxs = []int32{
	0, // 0: StateSubsets.subset:type_name -> StateSubset
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_generateState_proto_init() }
func file_generateState_proto_init() {
	if File_generateState_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_generateState_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateSubset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_generateState_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateSubsets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_generateState_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_generateState_proto_goTypes,
		DependencyIndexes: file_generateState_proto_depIdxs,
		MessageInfos:      file_generateState_proto_msgTypes,
	}.Build()
	File_generateState_proto = out.File
	file_generateState_proto_rawDesc = nil
	file_generateState_proto_goTypes = nil
	file_generateState_proto_depIdxs = nil
}
